export interface Topic {
  id: string;
  title: string;
  description: string;
  icon: string;
  coreConcepts: string[];
}

export const TOPICS: Topic[] = [
  {
    id: "neural-networks",
    title: "Neural Networks",
    description: "Backpropagation, gradient descent, activation functions, loss optimization, and architectures.",
    icon: "🧠",
    coreConcepts: [
      "Neurons & Layers",
      "Activation Functions",
      "Backpropagation",
      "Gradient Descent",
      "Loss Functions",
      "Overfitting & Regularization",
      "Learning Rate",
      "Weight Initialization",
      "Batch Normalization",
      "Convolutional Layers",
    ],
  },
  {
    id: "databases",
    title: "Databases",
    description: "Indexing, normalization, ACID, query optimization, and distributed storage.",
    icon: "🗄️",
    coreConcepts: [
      "ACID Properties",
      "Normalization",
      "Indexing",
      "Query Optimization",
      "Joins",
      "Transactions",
      "CAP Theorem",
      "Sharding",
      "Replication",
      "SQL vs NoSQL",
    ],
  },
  {
    id: "system-design",
    title: "System Design",
    description: "Load balancing, caching, microservices, consistency models, and scalability patterns.",
    icon: "⚙️",
    coreConcepts: [
      "Load Balancing",
      "Caching Strategies",
      "Microservices",
      "API Gateway",
      "Message Queues",
      "Consistency Models",
      "Database Partitioning",
      "CDN",
      "Rate Limiting",
      "Horizontal vs Vertical Scaling",
    ],
  },
  {
    id: "javascript",
    title: "JavaScript",
    description: "Closures, prototypes, event loop, promises, and modern ES6+ patterns.",
    icon: "⚡",
    coreConcepts: [
      "Closures",
      "Prototypal Inheritance",
      "Event Loop",
      "Promises & Async/Await",
      "Hoisting",
      "this Keyword",
      "Module Systems",
      "Destructuring & Spread",
      "WeakMap & WeakSet",
      "Generators & Iterators",
    ],
  },
  {
    id: "react",
    title: "React",
    description: "Component lifecycle, hooks, state management, reconciliation, and performance.",
    icon: "⚛️",
    coreConcepts: [
      "Virtual DOM & Reconciliation",
      "Hooks (useState, useEffect)",
      "Component Lifecycle",
      "Context API",
      "Memoization (memo, useMemo, useCallback)",
      "Refs & DOM Access",
      "Error Boundaries",
      "Suspense & Lazy Loading",
      "Controlled vs Uncontrolled",
      "Custom Hooks",
    ],
  },
  {
    id: "data-structures",
    title: "Data Structures",
    description: "Arrays, trees, graphs, hash tables, heaps, and algorithmic complexity.",
    icon: "🌳",
    coreConcepts: [
      "Big-O Notation",
      "Hash Tables",
      "Binary Search Trees",
      "Graphs & Traversal",
      "Heaps & Priority Queues",
      "Linked Lists",
      "Stacks & Queues",
      "Tries",
      "Dynamic Programming",
      "Sorting Algorithms",
    ],
  },
  {
    id: "operating-systems",
    title: "Operating Systems",
    description: "Processes, threads, memory management, scheduling, and concurrency.",
    icon: "🖥️",
    coreConcepts: [
      "Processes vs Threads",
      "Context Switching",
      "Memory Management",
      "Virtual Memory & Paging",
      "Deadlocks",
      "Mutex & Semaphores",
      "CPU Scheduling",
      "File Systems",
      "I/O Management",
      "Inter-Process Communication",
    ],
  },
  {
    id: "networking",
    title: "Computer Networks",
    description: "TCP/IP, HTTP, DNS, TLS, WebSockets, and network security fundamentals.",
    icon: "🌐",
    coreConcepts: [
      "OSI Model",
      "TCP vs UDP",
      "HTTP/HTTPS",
      "DNS Resolution",
      "TLS/SSL Handshake",
      "WebSockets",
      "REST vs GraphQL",
      "CORS",
      "Load Balancers & Proxies",
      "Network Security",
    ],
  },
  {
    id: "devops",
    title: "DevOps & CI/CD",
    description: "Docker, Kubernetes, pipelines, infrastructure as code, and monitoring.",
    icon: "🚀",
    coreConcepts: [
      "Docker & Containers",
      "Kubernetes Orchestration",
      "CI/CD Pipelines",
      "Infrastructure as Code",
      "Monitoring & Observability",
      "Blue-Green Deployments",
      "GitOps",
      "Service Mesh",
      "Secret Management",
      "Logging & Alerting",
    ],
  },
  {
    id: "security",
    title: "Cybersecurity",
    description: "Authentication, encryption, OWASP top 10, XSS, CSRF, and secure coding.",
    icon: "🔐",
    coreConcepts: [
      "Authentication vs Authorization",
      "OAuth 2.0 & JWT",
      "Encryption (Symmetric vs Asymmetric)",
      "SQL Injection",
      "XSS & CSRF",
      "OWASP Top 10",
      "Hashing & Salting",
      "HTTPS & Certificates",
      "Zero Trust Architecture",
      "Penetration Testing",
    ],
  },
  {
    id: "machine-learning",
    title: "Machine Learning",
    description: "Supervised/unsupervised learning, model evaluation, feature engineering, and bias.",
    icon: "🤖",
    coreConcepts: [
      "Supervised vs Unsupervised",
      "Bias-Variance Tradeoff",
      "Cross-Validation",
      "Feature Engineering",
      "Decision Trees & Random Forests",
      "SVM",
      "Clustering (K-Means, DBSCAN)",
      "Dimensionality Reduction (PCA)",
      "Ensemble Methods",
      "Model Evaluation Metrics",
    ],
  },
];
